### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by StripedBanana** [anxdpanic/plugin.video.twitch#279] opened 2017-04-25 18:10 UTC
Hi all

I noticed I couldn't open a lot of streams (seems to be random, but not sure). I just got a basic GUI message  that didn't display any information, so I dug into the ```.kodi/temp/kodi.log``` file, and found this every time I requested to open a stream and failed:

```
08:27:38.564 T:1563161584   ERROR: GetDirectory - Error getting
08:27:41.287 T:1546302448   ERROR: Previous line repeats 6 times.
08:27:41.287 T:1546302448  NOTICE: [xbmcswift2] Request for "/" matches rule for function "createMainListing"
08:27:44.184 T:1534063600  NOTICE: [xbmcswift2] Request for "/createListOfChannels/0/" matches rule for function "createListOfChannels"
08:27:47.445 T:1534063600  NOTICE: [xbmcswift2] Request for "/playLive/tsm_dyrus/-2/" matches rule for function "playLive"
08:27:49.210 T:1534063600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 42: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/__run__.py", line 7, in <module>
                                                sys.exit(PLUGIN.run())
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/exception.py", line 13, in wrapper
                                                handleTwitchException(error)
                                              File "/home/osmc/.kodi/addons/plugin.video.twitch/resources/lib/exception.py", line 27, in handleTwitchException
                                                PLUGIN.notify(PLUGIN.get_string(title), PLUGIN.get_string(msg), image=Images.ICON)
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 300, in notify
                                                (msg, title, delay, image))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 42: ordinal not in range(128)
                                            -->End of Python script error report<--
08:27:49.325 T:1958355888   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/tsm_dyrus/-2/]
```

And I think this line is very relevant: 
```
08:27:49.210 T:1534063600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 42: ordinal not in range(128)
```

FYI, I run the latest version of Kodi on my Raspberry Pi 3. It seems like a Python dependency has been updated and that it doesn't have the same behaviour on this function? I don't recall getting this error a few months ago, but now I have it on most streams (btw maybe only the streams with a weird character in title, or stream name cause issues? haven't verified).

Sorry for the long log file, didn't really know how to format it

**Comment by anxdpanic** [comment] 2017-04-27 15:37
The message/title that triggered that error looks to be a localized string, and masking the error that initially caused this notification to trigger. Can you provide which system language and Kodi language you are using so I can try to reproduce. Thanks

**Comment by StripedBanana** [comment] 2017-04-27 16:07
I'm not sure what you mean by 

> system language

and

> Kodi language

You probably mean which distribution I installed on my pi, that's true I didn't mention that: I use OSMC, downloaded [here](https://osmc.tv/download/) for Raspberry. The distro is up to date.

I just flashed it on my pi, and installed Twitch via the official repo already included. 

Btw I tried the alpha mentioned in the other issue, and so far it never crashed like this (well, not at all).

**Comment by anxdpanic** [comment] 2017-04-27 16:11
By system language I meant which language your OS used (english/french etc.) and same with Kodi, which language is the interface written in?

Thanks for confirming working with that version as well.

**Comment by StripedBanana** [comment] 2017-04-27 16:14
Oh ok! Indeed I'm pretty sure I chose french as language when I set things up. Might not ease the task I guess, with all the accents... though why some streams and not others? I don't recall seeing accents or weird stuff like that in the streams that failed to load

**Comment by anxdpanic** [comment] 2017-04-27 16:20
The error you posted was an error in the error handling, caused by a different error (resolved by alpha). You were seeing the error caused by a string(in your case would be in french) in the add-on error notification when trying to notify of the initial error.

**Comment by anxdpanic** [comment] 2017-04-27 18:17
#286 resolves the encoding in v1

**Closed as completed by anxdpanic** 2017-04-27 18:17 UTC
