### ISSUE TITLE
UnicodeDecodeError with Hebrew locale

### ISSUE THREAD

**Issue by haggaie** [anxdpanic/plugin.video.twitch#552] opened 2021-04-12 10:08 UTC
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.5.4
* Kodi Version: 18.9
* Kodi GUI Language: Hebrew
* Operating System: Windows
* Operating System Language: Hebrew

------

### Expected Behavior

Choosing to browse streams from the add-on menu, I expect to see a list of streams.

------

### Current Behavior

When using a Hebrew interface language in Kodi, I get an error instead, saying that an exception has been logged.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Set Kodi to interface to Hebrew
2. Open Twitch add-on / סייר / עמוד לשידור החי
3. See exception

------

### Log

Here's the exception from the log. Let me know if you need a more detailed log.

```
2021-04-12 13:00:03.443 T:18592 WARNING: script.module.python.twitch: API version |V5| is deprecated, update to |Helix| by |TBD|
2021-04-12 13:00:06.376 T:18592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xd7 in position 0: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\hagga\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\addon_runner.py", line 15, in <module>
                                                router.run(sys.argv)
                                              File "C:\Users\hagga\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\router.py", line 297, in run
                                                dispatcher.dispatch(mode, queries)
                                              File "C:\Users\hagga\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\addon\common\url_dispatcher.py", line 94, in dispatch
                                                self.func_registry[mode](*args, **kwargs)
                                              File "C:\Users\hagga\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\addon\error_handling.py", line 29, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\hagga\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\router.py", line 94, in _list_streams
                                                streams.route(twitch_api, stream_type, offset, platform)
                                              File "C:\Users\hagga\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\routes\streams.py", line 60, in route
                                                kodi.create_item(converter.stream_to_listitem(stream))
                                              File "C:\Users\hagga\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\addon\converter.py", line 301, in stream_to_listitem
                                                context_menu.extend(menu_items.add_blacklist(b64encode(channel[Keys.GAME].encode('utf-8', 'ignore')), channel[Keys.GAME], list_type='game'))
                                              File "C:\Users\hagga\AppData\Roaming\Kodi\addons\plugin.video.twitch\resources\lib\twitch_addon\addon\menu_items.py", line 65, in add_blacklist
                                                return run_plugin(i18n('add_blacklist') % ''.join(['[COLOR=white][B]', display_name, '[/B][/COLOR]']),
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 0: ordinal not in range(128)
                                            -->End of Python script error report<--
2021-04-12 13:00:06.405 T:26364   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.twitch/?mode=stream_list&stream_type=live
2021-04-12 13:00:06.417 T:42948   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twitch/?mode=stream_list&stream_type=live) failed
```

------

### Additional Information

I saw there was a similar issue (#378), which seems to have been closed already.

I also checked Kodi 19 and it worked fine. I could only reproduce the error on Kodi 18.9.

------

**Comment by DimmKG** [comment] 2021-05-14 08:49
This error happens, because functions like `add_blacklist`  do formatting of the byte string from the translation with a standard unicode string.
Here is an example:
```python
def add_blacklist(target_id, display_name, list_type='user'):
    #display_name = u'Resident Evil Village'
    import web_pdb; web_pdb.set_trace()
    translate = i18n('add_blacklist')    #Byte string  "Добавить в черный список %s"
    object_name = ''.join(['[COLOR=white][B]', display_name, '[/B][/COLOR]']) # = u'[COLOR=white][B]Resident Evil Village[/B][/COLOR]'
    result_name = translate % object_name    #Error! UnicodeDecodeError
    return run_plugin( result_name ,
                      {'mode': MODES.EDITBLACKLIST, 'target_id': target_id, 'name': display_name, 'list_type': list_type, 'refresh': True})
```

P.S In some cases, `dispay_name` can also be  a byte string ( '\xec\xb9\xa8\xec\xb0\xa9\xeb\xa7\xa8' - 침착맨 ) and `object_name.encode('utf-8')` will throw UnicodeDecodeError

Error also appears in:
https://github.com/anxdpanic/Twitch-on-Kodi/blob/1dceacf8c19f12fd682595f7f2ca83331e07e035/resources/lib/twitch_addon/routes/edit_blacklist.py#L31

https://github.com/anxdpanic/Twitch-on-Kodi/blob/1dceacf8c19f12fd682595f7f2ca83331e07e035/resources/lib/twitch_addon/addon/menu_items.py#L39

https://github.com/anxdpanic/Twitch-on-Kodi/blob/1dceacf8c19f12fd682595f7f2ca83331e07e035/resources/lib/twitch_addon/routes/edit_qualities.py#L42

https://github.com/anxdpanic/Twitch-on-Kodi/blob/1dceacf8c19f12fd682595f7f2ca83331e07e035/resources/lib/twitch_addon/routes/token_url.py#L26

**Comment by DimmKG** [comment] 2021-05-14 10:02
Steps to reproduce:
1. Set Kodi language to Hebrew or Russian
2. Open addon and choose the first menu entry (Featured streams)
3. Get the error

Log:  [kodi.log](https://github.com/anxdpanic/Twitch-on-Kodi/files/6478093/kodi.log)

**Comment by atomoc** [comment] 2021-05-14 15:35
Confirm I have the same error

**Comment by anxdpanic** [comment] 2021-05-14 16:15
Should be resolved in https://github.com/anxdpanic/Twitch-on-Kodi/releases/tag/2.5.6 it's also submitted to the official repository for review.

Thanks for highlighting the issue areas @DimmKG

**Comment by DimmKG** [comment] 2021-05-14 16:43
I confirm, that  [version 2.5.6](https://github.com/anxdpanic/Twitch-on-Kodi/releases/tag/2.5.6) works now with Russian and Hebrew language.

**Comment by efirshik** [comment] 2021-05-15 14:05
kodi 18.9
plugin.video.twitch-2.5.6
language Russian
error if open "following - live channels". 
log: https://termbin.com/iyia
but on english language all work.

**Comment by DimmKG** [comment] 2021-05-15 14:40
Looks like the info strings can also be byte strings and this code will cause crash:
https://github.com/anxdpanic/Twitch-on-Kodi/blob/0c893005e6ba4a2cd98a164e92733d5b18f9bb1a/resources/lib/twitch_addon/addon/converter.py#L466

The First case (normal):
![изображение](https://user-images.githubusercontent.com/8424428/118364671-a7005880-b5c3-11eb-8f0f-1624f87b23c4.png)

The Second case (with a problem):
![изображение](https://user-images.githubusercontent.com/8424428/118365204-e9c33000-b5c5-11eb-911a-949da0361250.png)

P.S This problem string is "Неизвестная игра" ("Unknown game" from translation)
![изображение](https://user-images.githubusercontent.com/8424428/118367163-280f1e00-b5cb-11eb-82a5-d1c83ade7950.png)

**Comment by haggaie** [comment] 2021-05-16 19:34
Hi,

I tried version 2.5.6 and it seemed to solve the issue for me.

Thanks!

**Comment by DimmKG** [comment] 2021-05-16 19:37
> Hi,
> 
> I tried version 2.5.6 and it seemed to solve the issue for me.
> 
> Thanks!

The bug is resolved, but not completely. If you meet a stream with unknown game, error appears again.

**Comment by efirshik** [comment] 2021-05-18 20:23
in version 2.5.7 with this fix russian language "following - live channels" open without any errors. all work, thanks!

**Closed as completed** 2021-06-25 00:46 UTC
Labels: bug
