### ISSUE TITLE
again API error in version 2.5.5

### ISSUE THREAD

**Issue by efirshik** [anxdpanic/plugin.video.twitch#560] opened 2021-05-10 19:06 UTC
kodi 18.9
plugin.video.twitch-2.5.5
script.module.python.twitch-2.0.16
log: https://termbin.com/thwt

**Comment by DimmKG** [comment] 2021-05-13 17:32
This is a problem with Russian string #30150 (add_blacklist). For some reason, that string doesn't support any Cyrillic character.
In Kodi 19, addon works normally.

**Comment by DimmKG** [comment] 2021-05-13 17:33
To reproduce this in Kodi 18, do this steps:
1. Set language to Russian

**Comment by DimmKG** [comment] 2021-05-13 17:36
To reproduce this bug in Kodi 18.9:
1. Set language to Russian
2. Open addon and choose the first menu entry ("Рекомендуемые трансляции")
3. Get an error
Log
[kodi.log](https://github.com/anxdpanic/Twitch-on-Kodi/files/6474102/kodi.log)

**Comment by DimmKG** [comment] 2021-05-14 09:05
Duplicate of #552

**Closed as completed** 2021-05-14 16:14 UTC
