### ISSUE TITLE
can not veiw some streams whiles other work { so far]

### ISSUE THREAD

**Issue by Baerht** [anxdpanic/plugin.video.twitch#253] opened 2017-03-31 03:23 UTC
I have noticed that some streams, the last couple of days,when I use streamlink to watch them , do not have the normal quality selections " source,High,medium, low and audio " but have " Best ,720p,480p,360p,Worst,160p, Audio_only'. the streams with theses different quality options lables I can not watch with the Kodi twitch addon and get a ' No live Data' pop up. I know these are just lables but it might also be that twitch is ready to roll out something

**Comment by cesarDevOp** [comment] 2017-03-31 09:19
@Baerht Which version are you using?
I testing this part and works fine.
In new videos uploaded on twitch it has more qualities than high, medium....

**Comment by anxdpanic** [comment] 2017-03-31 09:55
https://raw.githubusercontent.com/anxdpanic/__testing_repository/master/zips/plugin.video.twitch-1.4.6~alpha2.zip should resolve

**Comment by henriklb** [comment] 2017-03-31 16:46
Same issue here https://www.twitch.tv/lirik doesn't work. The zip file you linked won't install on my RPi2

**Comment by nrk666** [comment] 2017-03-31 17:40
I can confirm this, both "Lirik" and "Sacriel" (I'm a PUB fan, lol) yield "No Live Data Found" errors when attempting to view using Twitch Addon 1.4.5 on Kodi 17.1 while both worked fine earlier in the week.

**Comment by richhard1** [comment] 2017-03-31 17:54
Lirik is using the new twitch encoder today, hence 'no live data found' also the alpha zip file '1.4.6.alpha2.zip' does not install, it fails to install. Using Kodi 16.1 on VUDuo2+, currently at 1.4.5 through Kodi Add-on Manager. Help?

**Comment by cesarDevOp** [comment] 2017-03-31 19:33
I tested https://www.twitch.tv/lirik and works fine on 1.4.6-alpha2

I not tested the zip version, I replace the source code

**Comment by anxdpanic** [comment] 2017-03-31 20:27
I repacked the zip, sorry about that, I edited the previous comment with the new link

**Comment by richhard1** [comment] 2017-03-31 21:28
Worked a treat, great thanks!

**Comment by ryanruiner** [comment] 2017-03-31 21:46
How do I install this alpha on a kodi box? I am not sure how exactly I get the zip file installed.. thank you !!!

**Comment by richhard1** [comment] 2017-03-31 21:52
Well I ftp it across, update, then delete it. You can just save it to a USB stick, then install it.

**Comment by henriklb** [comment] 2017-03-31 22:12
thank you, the repack works fine

**Comment by Baerht** [comment] 2017-03-31 22:57
@ryanruiner https://kodicommunity.com/install-zip-file-kodi-device/

**Comment by Orphis** [comment] 2017-04-05 12:12
https://www.twitch.tv/synderen is also having issues. The source stream is tagged with "900p60 (source)". The m3u8 is looking like this:

`
#EXTM3U
#EXT-X-TWITCH-INFO:NODE="video-edge-c61a5c.arn03",MANIFEST-NODE-TYPE="weaver",CLUSTER="arn03",SUPPRESS="true",SERVER-TIME="1491394132.84",TRANSCODESTACK="2017TranscodeX264",USER-IP="...",SERVING-ID="0c79eb9c16804f02816ff5b798430cea",MANIFEST-NODE="video-edge-c61a5c.arn03",ABS="false",BROADCAST-ID="24972924752",STREAM-TIME="9412.83858705",MANIFEST-CLUSTER="arn03"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="chunked",NAME="900p60 (source)",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4137924,RESOLUTION=1600x900,CODECS="avc1.4D402A,mp4a.40.2",VIDEO="chunked"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p60",NAME="720p60",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3428381,RESOLUTION=1280x720,CODECS="avc1.77.31,mp4a.40.2",VIDEO="720p60"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p30",NAME="720p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2378381,RESOLUTION=1280x720,CODECS="avc1.77.31,mp4a.40.2",VIDEO="720p30"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="480p30",NAME="480p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1433381,RESOLUTION=852x480,CODECS="avc1.77.31,mp4a.40.2",VIDEO="480p30"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="360p30",NAME="360p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=750881,RESOLUTION=640x360,CODECS="avc1.77.31,mp4a.40.2",VIDEO="360p30"
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="160p30",NAME="160p",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=362381,RESOLUTION=284x160,CODECS="avc1.77.31,mp4a.40.2",VIDEO="160p30"
`

**Comment by cesarDevOp** [comment] 2017-04-05 15:29
@Orphis I tested synderen stream and it works.
In contrast, i dont have 900p60 as source on my list. I try 1080 and 720 with no problems.

**Comment by Orphis** [comment] 2017-04-05 18:29
I don't know where you got 1080p stream as the streamer doesn't support that resolution at all. Even going on the actual Twitch website, that resolution isn't available.

**Comment by richhard1** [comment] 2017-04-05 18:54
Orphis, his comment is valid. Twitch is using a new encoder (some streamers are testing), although an option isn't available to the viewer at 1080p, it is and will be an option in the near future. Currently you have to select 'source', ('high' is only 720/60p)

**Comment by Orphis** [comment] 2017-04-05 19:15
Well, I am selecting "source", but the plugin doesn't recognize which stream to pick at all, that's the issue.
This streamer is *not* streaming 1080p at all as shown with the playlist issued by Twitch.

The selection through quality "names" doesn't work at new entries need to be added all the time and it would be better to be able to automatically use the stream with highest bitrate or resolution.

**Comment by anxdpanic** [comment] 2017-04-05 23:31
Qualities aren't handled very well at the moment in this version, but content should work. I haven't completely resolved it for this version since I am trying to put my efforts into getting V2 complete. Qualities are handled differently and are working fine for that version.

- quality selection ask/source/bandwidth (clips excluded from bandwidth)
- add set default quality for stream/video/clips per channel

**Comment by anechol** [comment] 2017-04-12 14:24
Is there any idea of when this is getting released? I'm using Kodi via Fire Stick and just about every day there's another stream or three I can't view. Just about half the channels I'm following I haven't seen in about two weeks. Or could I at least get some help on how to install the alpha on Fire Stick?

**Comment by nrk666** [comment] 2017-04-12 22:16
You can always install the official Twitch app on a FireStick. If you link an Amazon Prime account, no more commercials either.

**Comment by janoscc** [comment] 2017-04-13 18:01
@anxdpanic thanks a lot, the 1.4.6-alpha update solved my 'No Live Data Found' issue! :)

**Comment by zaboris** [comment] 2017-04-18 19:44
@anxdpanic Thank you, the 1.4.6~alpha2 patch is very helpful, especially because the 2.0 version of twitch addon won't run on my older andriod device. 2.0 plugin crashes at start, I'm using jarvis kodi, can't install newer one, because of old andriod version).

**Comment by anxdpanic** [comment] 2017-04-18 19:49
The android/ios issues were just mentioned earlier, the latest updates to v2 should hopefully have that resolved now. Can follow that at #235

**Comment by sirsquall** [comment] 2017-04-20 16:09
I have the same issue, I'm using the version 1.4.5 and in the log file, I have this message:
UnicodeEncodeError: 'ascii' codec can't encode character u\xe9 in position 42: ordinal not in range 128

And some other channel are working well.

**Comment by MrSprigster** [comment] 2017-04-20 19:35
Try the 2.0 Beta release, it should drastically improve things for you.

**Comment by sirsquall** [comment] 2017-04-20 21:21
Hi,

Thank you, do you know when the beta will be released?

**Comment by MrSprigster** [comment] 2017-04-20 21:32
Should be fairly soon, once the last few bugs have been ironed out.

If you have any issues with the beta on your platform, please do report
them here.

**Comment by sirsquall** [comment] 2017-04-20 21:44
Ok so I will wait the release to install the 2.0 

Thank you very much, and good job guys

**Comment by anxdpanic** [comment] 2017-04-26 11:37
Closed by #282

**Closed as completed by anxdpanic** 2017-04-26 11:37 UTC
